### ISSUE TITLE
add MODE command

### ISSUE THREAD

**Issue by rinonaito** [IRC-WIR/ft_irc#10]

**Comment by paphio-kitsuki** [comment]
コード調査
ERR_NEEDMOREPARAMS ... パラメータが0個の場合 -> 要対応
ERR_CHANOPRIVSNEEDED ... オペレーターでないユーザーがコマンドを実行した場合 -> 要対応
ERR_NOTONCHANNEL ... 謎 -> 対応不可
RPL_BANLIST ... bモードを指定した際にパラメータが2個の場合 -> 対応不要
ERR_UNKNOWNMODE ... 存在しないモードを指定した場合 -> 要対応
RPL_CHANNELMODEIS ... パラメータが一つ(かつそれが存在するチャンネル)の場合 -> 余裕があれば対応
ERR_NOSUCHNICK ... 存在しないニックネームを指定した場合 -> 対応不要
ERR_KEYSET ... kモードの時、+kの時`: `を含んでいたり、-kの時正しいキーを入力できていなかった場合 -> 要対応
RPL_ENDOFBANLIST ... RPL_BANLISTの最後に出力されるもの -> 対応不要
ERR_NOSUCHCHANNEL ... 存在しないチャンネルを指定した場合 -> 要対応
ERR_USERSDONTMATCH ... MODEの対象にユーザーを指定した際、それに対応する権限がない場合 -> 対応不要
ERR_UMODEUNKNOWNFLAG ... MODEの対象にユーザーを指定した際、存在しないモードを指定した場合 -> 対応不要
RPL_UMODEIS ... パラメータが一つ(かつそれが存在するユーザー)の場合 -> 対応不要

**Comment by paphio-kitsuki** [comment]
キー(kモード)について
キーを設定する際、32文字以上を指定すると、32文字に自動的に切り捨てられる
キーを解除する際は、32文字以上を設定してもそのまま受け付けて、比較される

**Comment by paphio-kitsuki** [comment]
もともとのモードと同じようにモードを指定した場合
ex. +iのチャンネルに対して MODE チャンネル +i や、なんのモードもないチャンネルに対して MODE チャンネル -i など

-> 無視される

**Comment by paphio-kitsuki** [comment]
複数モード指定時
それぞれに対して、存在するモードか、パラメータが足りてるか判定される
エラーの場合、それぞれエラー文を出力
成功の場合、成功した分をまとめて一行で出力

-> 対応したくない...

**Comment by paphio-kitsuki** [comment]
人数制限(lモード)について
とても大きすぎる値 ... 0になる
大きすぎる値 ... エラー
負の値 ... エラー
 -> 面倒なのですべて0に統一
数字以外が来た場合 ... atoiのような挙動

※所属人数より小さい値を設定した場合 ... 何も起こらない。新たに入れなくなるだけ。

**Comment by paphio-kitsuki** [comment]
+kの時`: `を含んでいた場合・+-ko, +lの時3つ目のパラメータが空の場合、-lの時負の数の場合
 -> 独自に定義したエラー`ERR_WRONGMODEPARAMS`を設定する

**Comment by paphio-kitsuki** [comment]
テストする際にmain関数に書いたコード
```
	Database d("");
	d.CreateUser(10);
	d.CreateUser(20);
	Event* event = new Event(10, 0);
	event->set_command(Command::kJoin);
	std::vector<std::string> vec;
	vec.push_back("#a");
	event->set_command_params(vec);
	d.CheckEvent(event);
	const Channel& channel = d.CreateChannel(event->get_executer(), "#a");
	ChannelEvent* channel_event = new ChannelEvent(*event, channel);
	delete event;
	event = channel_event;
	d.ExecuteEvent(*event);
	delete event;
	while (true) {
		Event* event = new Event(20, 0);
		event->set_command(Command::kMode);
		std::vector<std::string> vec;
		vec.clear();
		vec.push_back("#a");
		while (true) {
			std::string s;
			std::cin >> s;
			if (s == "fin")
				break ;
			vec.push_back(s);
		}
		event->set_command_params(vec);
		event->set_do_nothing(false);
		d.CheckEvent(event);
		if (!event->is_do_nothing()) {
			std::cout << "10:" << d.ExecuteEvent(*event)[10] << std::endl;
			std::cout << "20:" << d.ExecuteEvent(*event)[20] << std::endl;
		}
		delete event;
	}
```

**Comment by weijuan82113** [comment]
> テストする際にmain関数に書いたコード
> 
> ```
> 	Database d("");
> 	d.CreateUser(10);
> 	d.CreateUser(20);
> 	Event* event = new Event(10, 0);
> 	event->set_command(Command::kJoin);
> 	std::vector<std::string> vec;
> 	vec.push_back("#a");
> 	event->set_command_params(vec);
> 	d.CheckEvent(event);
> 	const Channel& channel = d.CreateChannel(event->get_executer(), "#a");
> 	ChannelEvent* channel_event = new ChannelEvent(*event, channel);
> 	delete event;
> 	event = channel_event;
> 	d.ExecuteEvent(*event);
> 	delete event;
> 	while (true) {
> 		Event* event = new Event(20, 0);
> 		event->set_command(Command::kMode);
> 		std::vector<std::string> vec;
> 		vec.clear();
> 		vec.push_back("#a");
> 		while (true) {
> 			std::string s;
> 			std::cin >> s;
> 			if (s == "fin")
> 				break ;
> 			vec.push_back(s);
> 		}
> 		event->set_command_params(vec);
> 		event->set_do_nothing(false);
> 		d.CheckEvent(event);
> 		if (!event->is_do_nothing()) {
> 			std::cout << "10:" << d.ExecuteEvent(*event)[10] << std::endl;
> 			std::cout << "20:" << d.ExecuteEvent(*event)[20] << std::endl;
> 		}
> 		delete event;
> 	}
> ```

**Comment by weijuan82113** [comment]
テストコードを書いてありがとうございます、
このコードで結合試験を作れそうですね、
グーグルテストで自動化できるかを確認してみませんか？
