### ISSUE TITLE
add USER command

### ISSUE THREAD

**Issue by rinonaito** [IRC-WIR/ft_irc#11]
[USERコマンドについての調査①](https://github.com/orgs/IRC-WIR/projects/2?pane=issue&itemId=80633361)

↑ エラーの優先順位は気にしないことにしたので、この調査はあくまで参考程度

**Comment by paphio-kitsuki** [comment]
[USERコマンドについての調査②](https://github.com/orgs/IRC-WIR/projects/2?pane=issue&itemId=85612125)

**Comment by weijuan82113** [comment]
動作確認ありがとうございます。
自分も確認を取れましたので、修正をマージします。
