### ISSUE TITLE
add JOIN command

### ISSUE THREAD

**Issue by rinonaito** [IRC-WIR/ft_irc#6]

**Comment by paphio-kitsuki** [comment]
調査結果

通常動作
join #a
返信メッセージ
:a!a@localhost JOIN :#a
:localhost 353 a #a :@a
:localhost 366 a #a :End of /NAMES list

通常動作(所属チャンネルに新規メンバーが参加した場合)
 返信メッセージ
:e!a@localhost JOIN :#b

すでに所属しているチャンネルにJOIN
join #b
 返信メッセージ無し

パラメータ不足
join
返信メッセージ
:localhost 461 a JOIN :Not enough parameters.

招待限定
join #a
返信メッセージ
:localhost 473 e JOIN :Cannot join channel (+i)

不正キー
join #a :aaa
返信メッセージ
:localhost 475 e JOIN :Cannot join channel (+k)

チャンネルメンバー数が最大
join #a
返信メッセージ
:localhost 471 e JOIN :Cannot join channel (+l)

チャンネル名の形式が不正
join a
返信メッセージ
:localhost 403 e JOIN :No such channel

自身が所属するチャンネル数が最大
join #k
返信メッセージ
:localhost 405 a JOIN :You have joined too many channels
