### ISSUE TITLE
add INVITE command

### ISSUE THREAD

**Issue by rinonaito** [IRC-WIR/ft_irc#7]

**Comment by paphio-kitsuki** [comment]
コード調査
ERR_NEEDMOREPARAMS ... 発生を確認できず -> 実装不可能
ERR_NOSUCHNICK ... 対象となるユーザーが存在しない場合 -> 要実装
ERR_NOTONCHANNEL ... 自分が招待先のチャンネルに所属していない場合 -> 要実装
ERR_USERONCHANNEL ... 対象となるユーザーがすでに招待先のチャンネルに所属している場合 -> 要実装
ERR_CHANOPRIVSNEEDED ... 自分がオペレーターではない場合 -> 要実装
RPL_INVITING ... 対象の招待に成功した場合に招待主に送られるメッセージ -> 要実装
RPL_AWAY ... AWAYコマンドに関連するものらしい -> 実装不要

rfcには無いけどirssiでは発生する、かつ発生させたいコード
ERR_NOSUCHCHANNEL ... 対象となるチャンネルが存在しない場合 -> 要実装
RPL_INVITELIST (336)
RPL_ENDOFINVITELIST (337)
 -> パラメータ不足のとき、ERR_NEEDMOREPARAMSの代わりに表示されていたもの。現在自分が招待されているチャンネルの情報を表示する。

**Comment by paphio-kitsuki** [comment]
所属中のチャンネルにおいて、ほかのユーザーがINVITEを実行すると、
`:irc.local NOTICE #a :*** d invited a into the channel`
という風にNOTICEコマンドで知らせてくるが、NOTICEは実装対象外なので無視する

**Comment by paphio-kitsuki** [comment]
招待された側
:d!a@127.0.0.1 INVITE a :#a
招待した側
:irc.local 341 d a :#a
パラメータ不足
:irc.local 336 a :#a
:irc.local 337 a :End of INVITE list
